default_roles:
  - system
  - yay
  - flatpak
  - git
  - waybar
  - zsh
  - gimp
  - fonts
  - kitty
  - vscodium
  - typst
  - yt-dlp
  - gallery-dl
  - fightcade
  - fastfetch
  - es-de
  - aria2
  - rmpc
  - mpv
  - starship

git_user_name: "marshfellow42"