---
- name: "{{ role_name }} | Check if yay is installed"
  ansible.builtin.command: command -v yay
  register: yay_check
  changed_when: false
  failed_when: false

- name: "{{ role_name }} | Install dependencies for yay"
  kewlfft.aur.aur:
    name:
      - git
      - base-devel
    state: present
  become: true
  become_user: aur_builder
  when: yay_check.rc != 0

- name: "{{ role_name }} | Clone yay AUR repo"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: "{{ ansible_facts['user_dir'] }}/yay"
  when: yay_check.rc != 0
  become: false

- name: "{{ role_name }} | Build and install yay"
  ansible.builtin.command: makepkg -si --noconfirm
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/yay"
  when: yay_check.rc != 0
  become: false

- name: "{{ role_name }} | Generate yay development package database"
  ansible.builtin.command: yay -Y --gendb
  when: yay_check.rc != 0
  become: false

- name: "{{ role_name }} | Enable permanent devel package updates"
  ansible.builtin.command: yay -Y --devel --save
  when: yay_check.rc != 0
  become: false

- name: "{{ role_name }} | Keep sudo privileges alive"
  ansible.builtin.command: yay --sudoloop --save
  when: yay_check.rc != 0
  become: false

- name: "{{ role_name }} | Remove yay build directory"
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/yay"
    state: absent
  when: yay_check.rc != 0

- name: "{{ role_name }} | Install essential apps"
  kewlfft.aur.aur:
    name:
      - librewolf-bin
      - rofi-wayland
      - awww
      - mpv
      - qbittorrent
      - webapp-manager
      - man-db
      - man-pages
      - netbird-bin
      - syncthing
      - vlc
      - gamemode
      - lib32-gamemode
    state: present
  become: true
  become_user: aur_builder

- name: "{{ role_name }} | Enable syncthing service"
  ansible.builtin.systemctl:
    name: syncthing.service

- name: "{{ role_name }} | Install media apps"
  kewlfft.aur.aur:
    name:
      - ffmpeg
      - imagemagick
      - makemkv
      - whipper
    state: present
  become: true
  become_user: aur_builder

- name: "{{ role_name }} | Install art apps"
  kewlfft.aur.aur:
    name:
      - aseprite
      - lmms
    state: present
  become: true
  become_user: aur_builder

- name: "{{ role_name }} | Install privacy apps"
  kewlfft.aur.aur:
    name:
      - mullvad-browser-bin
      - veracrypt
      - keepassxc
    state: present
  become: true
  become_user: aur_builder

- name: "{{ role_name }} | Install dev tools"
  kewlfft.aur.aur:
    name:
      - scrcpy
      - gnupg
      - jq
      - ripgrep
      - fzf
      - zoxide
    state: present
  become: true
  become_user: aur_builder

- name: "{{ role_name }} | Install the tools for Majora's Mask Recomp modding"
  kewlfft.aur.aur:
    name:
      - clang
      - make
      - lld
      - zip
    state: present
  become: true
  become_user: aur_builder

- name: "{{ role_name }} | Install emulators"
  kewlfft.aur.aur:
    name:
      - rpcs3-bin
      - shadps4-qtlauncher-bin
      - vita3k-git
      - eden-pgo-bin
    state: present
  become: true
  become_user: aur_builder

- name: "{{ role_name }} | Install gaming apps"
  kewlfft.aur.aur:
    name:
      - freesmlauncher
      - osu-lazer-bin
      - steam
      - lutris
    state: present
  become: true
  become_user: aur_builder

- name: "{{ role_name }} | Install writing tools"
  kewlfft.aur.aur:
    name:
      - obsidian-appimage
      - timelineproject-hg
    state: present
  become: true
  become_user: aur_builder