---
- name: "Yay | {{ ansible_facts['distribution'] }} | Check if yay is installed"
  ansible.builtin.command: command -v yay
  register: yay_check
  changed_when: false
  failed_when: false

- name: "Yay | {{ ansible_facts['distribution'] }} | Install dependencies for yay"
  kewlfft.aur.aur:
    name:
      - git
      - base-devel
    state: present
  become: true
  become_user: aur_builder
  when: yay_check.rc != 0

- name: "Yay | {{ ansible_facts['distribution'] }} | Clone yay AUR repo"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: "{{ ansible_facts['user_dir'] }}/yay"
  when: yay_check.rc != 0
  become: false

- name: "Yay | {{ ansible_facts['distribution'] }} | Build and install yay"
  ansible.builtin.command: makepkg -si --noconfirm
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/yay"
  when: yay_check.rc != 0
  become: false

- name: "Yay | {{ ansible_facts['distribution'] }} | Generate yay development package database"
  ansible.builtin.command: yay -Y --gendb
  when: yay_check.rc != 0
  become: false

- name: "Yay | {{ ansible_facts['distribution'] }} | Enable permanent devel package updates"
  ansible.builtin.command: yay -Y --devel --save
  when: yay_check.rc != 0
  become: false

- name: "Yay | {{ ansible_facts['distribution'] }} | Remove yay build directory"
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/yay"
    state: absent
  when: yay_check.rc != 0

- name: "Yay | {{ ansible_facts['distribution'] }} | Install essential apps using yay"
  kewlfft.aur.aur:
    name:
      - librewolf-bin
      - rofi-wayland
      - swww
      - mpv
      - qbittorrent
    state: present
  become: true
  become_user: aur_builder

- name: "Yay | {{ ansible_facts['distribution'] }} | Install media apps using yay"
  kewlfft.aur.aur:
    name:
      - ffmpeg
      - imagemagick
      - makemkv
      - whipper
    state: present
  become: true
  become_user: aur_builder

- name: "Yay | {{ ansible_facts['distribution'] }} | Install art apps using yay"
  kewlfft.aur.aur:
    name:
      - aseprite
      - lmms
      - mpd
      - rmpc
    state: present
  become: true
  become_user: aur_builder

- name: "Yay | {{ ansible_facts['distribution'] }} | Install privacy apps using yay"
  kewlfft.aur.aur:
    name:
      - mullvad-browser-bin
      - veracrypt
      - keepassxc
    state: present
  become: true
  become_user: aur_builder

- name: "Yay | {{ ansible_facts['distribution'] }} | Install dev tools using yay"
  kewlfft.aur.aur:
    name:
      - scrcpy
      - gnupg
    state: present
  become: true
  become_user: aur_builder

- name: "Yay | {{ ansible_facts['distribution'] }} | Install emulators using yay"
  kewlfft.aur.aur:
    name:
      - rpcs3-bin
      - cemu
      - shadps4-git
      - vita3k-git
      - eden
    state: present
  become: true
  become_user: aur_builder

- name: "Yay | {{ ansible_facts['distribution'] }} | Install gaming apps using yay"
  kewlfft.aur.aur:
    name:
      - freesmlauncher
      - osu-lazer-bin
      - steam
      - lutris
    state: present
  become: true
  become_user: aur_builder

- name: "Yay | {{ ansible_facts['distribution'] }} | Install writing tools using yay"
  kewlfft.aur.aur:
    name:
      - obsidian-appimage
      - timelineproject-hg
    state: present
  become: true
  become_user: aur_builder