"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 4

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = "\uE0B0"
    background = '#ffe9aa'
    foreground = '#100e23'
    template = ' \uF0E7 '

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = "\uE0B0"
    background = '#ffffff'
    foreground = '#100e23'
    template = ' {{ .UserName }}@{{ .HostName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = "\uE0B0"
    background = '#91ddff'
    foreground = '#100e23'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      folder_icon = "\uF115"
      folder_separator_icon = " \uE0B1 "
      home_icon = "\uEB06"
      style = 'agnoster'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = "\uE0B0"
    background = '#95ffa4'
    foreground = '#193549'
    template = ' {{ .HEAD }} '

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    powerline_symbol = "\uE0B0"
    background = '#906cff'
    foreground = '#100e23'
    template = ' \uE235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'status'
    style = 'powerline'
    powerline_symbol = "\uE0B0"
    background = '#ff8080'
    foreground = '#ffffff'
    template = ' {{ reason .Code }} '