---
- name: "{{ role_name }} | Detect desktop environment"
  ansible.builtin.command: printenv XDG_CURRENT_DESKTOP
  register: desktop_env
  changed_when: false
  failed_when: false

- name: "{{ role_name }} | Normalize desktop environment"
  ansible.builtin.set_fact:
    current_desktop: "{{ desktop_env.stdout.split(':')[0] | lower }}"

- name: "{{ role_name }} | Hyprland specific tasks"
  when: current_desktop == "hyprland"
  block:

    - name: "{{ role_name }} | Symlink hypr folder"
      ansible.builtin.file:
        src: "{{ _files_path }}/hypr"
        dest: "{{ ansible_facts['user_dir'] }}/.config/hypr"
        state: link
        force: yes

    - name: "{{ role_name }} | Test if Dolphin File Manager file preferences are okay"
      ansible.builtin.command: kbuildsycoca6 --noincremental
      register: build_dolphin

    - name: "{{ role_name }} | Register Dolphin file menu"
      when: build_dolphin != 0
      block:

        - name: "{{ role_name }} | Install xdg-menu"
          ansible.builtin.package:
            name: archlinux-xdg-menu 
            state: present
          become: true

        - name: "{{ role_name }} | Test if Dolphin File Manager file preferences are okay"
          ansible.builtin.command: update-desktop-database
          become: true

        - name: Rename arch-applications.menu to applications.menu
          ansible.builtin.command: mv arch-applications.menu applications.menu
          args:
            chdir: /etc/xdg/menus
            removes: arch-applications.menu  # Only runs if the source file exists (makes it idempotent)
          become: true

        - name: "{{ role_name }} | Test if Dolphin File Manager file preferences are okay (again)"
          ansible.builtin.command: kbuildsycoca6 --noincremental