---
- name: DotFiles Config
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

    - name: Detect Sudo
      ansible.builtin.import_tasks: pre_tasks/detect_sudo.yml
      tags:
        - always

  tasks:
    - name: Run roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ default_roles | reject('in', exclude_roles | default([])) | list }}"
      when: "ansible_run_tags | list == ['all'] or item in ansible_run_tags"