---
- name: "EmulationStation Desktop Edition | {{ ansible_facts['distribution'] }} | Install emulationstation-de"
  kewlfft.aur.aur:
    name:
      - emulationstation-de
    state: present
  become: true
  become_user: aur_builder