---
- name: "EmulationStation Desktop Edition | {{ ansible_facts['distribution'] }} | Install emulationstation-de"
  kewlfft.aur.aur:
    use: yay
    name:
      - emulationstation-de
    state: present
  become: yes
  become_user: aur_builder