---
- name: "VSCodium | {{ ansible_facts['distribution'] }} | Install vscodium"
  kewlfft.aur.aur:
    name:
      - vscodium-bin
      - vscodium-marketplace
  become: true
  become_user: aur_builder