---
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

- name: "{{ role_name }} | Install dolphin-plugins"
  ansible.builtin.package:
    name: dolphin-plugins
    state: present
  become: true

- name: "{{ role_name }} | Install rate-mirrors"
  ansible.builtin.package:
    name: rate-mirrors
    state: present
  become: true

- name: "{{ role_name }} | Install cronie"
  ansible.builtin.package:
    name: cronie
    state: present
  become: true

- name: "{{ role_name }} | Schedule an update of pacman mirrors every week using rate-mirrors"
  ansible.builtin.cron:
    name: "arch mirrors weekly update"
    special_time: "weekly"
    job: "rate-mirrors --entry-country BR --protocol https arch | sudo tee /etc/pacman.d/mirrorlist"
    state: present

- name: "{{ role_name }} | Ensure pipewire is installed"
  ansible.builtin.package:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - wireplumber
      - jack2
    state: present
  become: true

- name: "{{ role_name }} | Enable pipewire socket"
  ansible.builtin.systemd_service:
    name: pipewire.socket

- name: "{{ role_name }} | Enable pipewire-pulse socket"
  ansible.builtin.systemd_service:
    name: pipewire-pulse.socket

- name: "{{ role_name }} | Enable wireplumber socket"
  ansible.builtin.systemd_service:
    name: wireplumber.socket

- name: "{{ role_name }} | Install playerctl"
  ansible.builtin.package:
    name: playerctl
    state: present
  become: true

- name: "{{ role_name }} | Install brightnessctl"
  ansible.builtin.package:
    name: brightnessctl
    state: present
  become: true

- name: "{{ role_name }} | Install ark"
  ansible.builtin.package:
    name: ark
    state: present
  become: true

- name: "{{ role_name }} | Install 7zip"
  ansible.builtin.package:
    name: 7zip
    state: present
  become: true

- name: "{{ role_name }} | Define Dolphin file manager as default for opening directories on other apps"
  ansible.builtin.command: xdg-mime default org.kde.dolphin.desktop inode/directory

- name: "{{ role_name }} | Install screenshot tools"
  ansible.builtin.package:
    name:
      - grim
      - wl-clipboard
      - satty
    state: present
  become: true

- name: "{{ role_name }} | Install Dolphin file manager tools"
  ansible.builtin.package:
    name:
      - ark
      - audiocd-kio
      - baloo
      - dolphin-plugins
      - kio-admin
      - kompare
      - ffmpegthumbs
      - icoutils
      - kdegraphics-thumbnailers
      - kimageformats
      - libappimage
      - qt6-imageformats
      - resvg
      - taglib
    state: present
  become: true

- name: "{{ role_name }} | Symlink Dolphin service menu folder to .local/share"
  ansible.builtin.file:
    src: "{{ _files_path }}/servicemenus"
    dest: "{{ ansible_facts['user_dir'] }}/.local/share/kio/servicemenus"
    state: link

- name: "{{ role_name }} | Install a sound processing tool"
  ansible.builtin.package:
    name:
      - sox
    state: present
  become: true

- name: "{{ role_name }} | Symlink usb-sound.sh to usr/local/bin"
  ansible.builtin.file:
    src: "{{ _files_path }}/udev/usb-sound.sh"
    dest: "/usr/local/bin/usb-sound.sh"
    state: link
  become: true

- name: "{{ role_name }} | Symlink udev rules"
  ansible.builtin.file:
    src: "{{ _files_path }}/udev/99-usb-sound.rules"
    dest: "/etc/udev/rules.d/99-usb-sound.rules"
    state: link
  become: true

- name: "{{ role_name }} | Reload udev rules"
  ansible.builtin.command: udevadm control --reload-rules
  become: true

- name: "{{ role_name }} | Install jq"
  ansible.builtin.package:
    name:
      - jq
    state: present
  become: true

# To fix the microphone from sounding like a demon took over it, just install alsa-utils, go to alsamixer, press F6 to select your actual sound card (instead of <default>), press F5 to see all sound devices, then go to Internal (Internal Mic Boost) and put it on 0.

# To make screen capture work, start the xdg-desktop-portal, and the hyprland already has the autostart ready on config
# To check if xdg-desktop-portal is inactive (dead), run 'systemctl --user status xdg-desktop-portal'

# If it is, then the settings should be like this

# ~ ❯ systemctl --user cat xdg-desktop-portal.service
# [Unit]
# Description=Portal service
# PartOf=graphical-session.target
# #Requisite=graphical-session.target   # removed = workaround
# Requires=dbus.service
# After=dbus.service graphical-session-pre.target

# [Service]
# Type=dbus
# BusName=org.freedesktop.portal.Desktop
# ExecStart=/usr/lib/xdg-desktop-portal
# Slice=session.slice

# Then restart the xdg-desktop-portal, with 'systemctl --user restart xdg-desktop-portal'