---
- name: Flatpak | Check if flatpak is installed
  ansible.builtin.command: command -v flatpak
  register: flatpak_installed
  changed_when: false
  failed_when: false

- name: Flatpak | Install and configure flatpak
  when: flatpak_installed.rc != 0
  block:

    - name: "Flatpak | Install flatpak"
      ansible.builtin.package:
        name: flatpak
        state: present
      become: true

    - name: "Flatpak | Add Flathub remote"
      community.general.flatpak_remote:
        name: "flathub"
        flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
        state: present

    - name: Flatpak | Add Dolphin Emulator remote
      community.general.flatpak_remote:
        name: "dolphin-emu"
        flatpakrepo_url: "https://flatpak.dolphin-emu.org/releases.flatpakrepo"
        state: present

    - name: "Flatpak | Detect desktop environment"
      ansible.builtin.command: systemctl get-default
      register: flatpak_systemd_target
      changed_when: false
      failed_when: false
      check_mode: false

    - name: "Flatpak | Set desktop environment fact"
      ansible.builtin.set_fact:
        flatpak_is_desktop: "{{ flatpak_systemd_target.stdout == 'graphical.target' }}"

    - name: "Flatpak | Install desktop applications"
      community.general.flatpak:
        name:
          - org.mozilla.Thunderbird
        state: present
        remote: flathub
      when: flatpak_is_desktop

    - name: "Flatpak | Install media applications"
      community.general.flatpak:
        name:
          - com.github.iwalton3.jellyfin-media-player
        state: present
        remote: flathub
      when: flatpak_is_desktop

    - name: "Flatpak | Install art applications"
      community.general.flatpak:
        name: 
          - com.obsproject.Studio
          - org.kde.kdenlive
          - org.tenacityaudio.Tenacity
          - org.kde.krita
          - org.inkscape.Inkscape
          - org.blender.Blender
          - org.darktable.Darktable
        state: present
        remote: flathub
      when: flatpak_is_desktop

    - name: "Flatpak | Install privacy applications"
      community.general.flatpak:
        name:
          - org.torproject.torbrowser-launcher
        state: present
        remote: flathub
      when: flatpak_is_desktop

    - name: "Flatpak | Install emulators"
      community.general.flatpak:
        name:
          - net.pcsx2.PCSX2
          - org.duckstation.DuckStation
          - org.ppsspp.PPSSPP
        state: present
        remote: flathub
      when: flatpak_is_desktop

    - name: "Flatpak | Install Dolphin Emulator"
      community.general.flatpak:
        name: org.DolphinEmu.dolphin-emu
        state: present
        remote: dolphin-emu
      when: flatpak_is_desktop
      
    - name: "Flatpak | Install gaming applications"
      community.general.flatpak:
        name:
          - net.lutris.Lutris
          - com.feaneron.Boatswain
          - org.vinegarhq.Sober
          - io.github.marco_calautti.DeltaPatcher
        state: present
        remote: flathub
      when: flatpak_is_desktop