# ==========    GENERAL    ==========
keep-open=yes
autocreate-playlist=same

# ==========    SCREENSHOT    ==========
screenshot-template="mpvshot - %F - %wHh%wMm%wSs%wT"

screenshot-format=webp
screenshot-webp-lossless=yes

screenshot-high-bit-depth=yes
screenshot-tag-colorspace=yes

# ==========    PRIORITY    ==========
alang=en,eng,ja,jp,jpn
slang=en,eng,ja,jp,jpn

# ==========    VIDEO    ==========
vo=gpu-next
gpu-api=vulkan
hwdec=vulkan,auto
target-colorspace-hint=yes
target-contrast=auto

# ==========    AUDIO    ==========
volume=100
volume-max=100
audio-file-auto=fuzzy

# ==========    DEBAND    ==========
deband=yes
deband-iterations=4
deband-threshold=48
deband-range=24
deband-grain=16