---
- name: "{{ role_name }} | Detect desktop environment"
  ansible.builtin.command: printenv XDG_CURRENT_DESKTOP
  register: desktop_env
  changed_when: false
  failed_when: false

- name: "{{ role_name }} | Normalize desktop environment"
  ansible.builtin.set_fact:
    current_desktop: "{{ desktop_env.stdout.split(':')[0] | lower }}"

- name: "{{ role_name }} | Hyprland specific tasks"
  when: current_desktop == "hyprland"
  block:

    - name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
      ansible.builtin.stat:
        path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
      register: distribution_config

    - name: "{{ role_name }} | Run OS Tasks: {{ ansible_facts['distribution'] }}"
      ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
      when: distribution_config.stat.exists