---
- name: "{{ role_name }} | Install all necessary fonts"
  kewlfft.aur.aur:
    name:
      - ttf-jetbrains-mono-nerd
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - ttf-courier-prime
      - ttf-material-symbols-variable
    state: present
  become: true
  become_user: aur_builder